### PR TITLE
Sensorics v5.2.1 Release

### PR DESCRIPTION
**Pull request by SerhatSurguvec**
**Description**
Sensorics v5.2.1 Release

### CODE REVIEW

**Comment by srishti77** [comment]
LGTM

**Comment by Nicba1010** [comment]
Right now version name is 5.2.4 so i suggest changing the original message or the title of this PR

**Comment by grubelic** [comment]
**Tested actions and publishers**

Actions: 
- Tested accelerometer, magnetometer and gyroscope triggered actions with notification, vibration and alarm outcomes (we don't have TTS so that outcome wasn't tested).
- Tested action activation / deactivation through Switch in ActionDetailsActivity, by starting / stopping scan and by activating / deactivating all in devices menu.
- Tested adding / removing actions.


Backends:
- Tested establishing connection to mqtt and http servers (Google IOT Cloud requires setting up a payment method, so it wasn't tested).
- Tested adding, sharing, importing, exporting and removing backend models.

**Comment by borna-mdn** [comment]
Deprecated

**Pull request closed without merging**
